services:
  database:
    container_name: post_api
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: posts
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 60s

volumes:
  database_data: